<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 17.10.20
 * Time: 13:40
 */
include_once 'custom/include/MVC/View/views/view.detail.php';

class DIGIT_TASKViewDetail extends CustomViewDetail {
    public function preDisplay()
    {
        User_RAM::check_Access($this);

        //указываем ссылку на tpl
        if (file_exists('modules/DIGIT_TASK/tpls/DetailView.tpl')) {
            $tpl = 'modules/DIGIT_TASK/tpls/DetailView.tpl';
        }
        $metadataFile = $this->getMetaDataFile();
        $this->dv = new DetailView2();
        $this->dv->ss =& $this->ss;
        if (!empty($tpl)) {
            $this->dv->setup($this->module, $this->bean, $metadataFile, $tpl);
        } else {
            $this->dv->setup($this->module, $this->bean, $metadataFile, get_custom_file_if_exists('include/DetailView/DetailView.tpl'));
        }
    }

    public function display(){
        /*
         * Добавляем данные по связям вакансий и кандидатов         *
         */
        require_once 'custom/include/CustomClass/tags_custom_class.php';
        $tcc = new tags_custom_class();
        $tcc->getTagsList(true);
        $this->dv->ss->assign("tags_list", $tcc->tagsList);

        parent::display(); // TODO: Change the autogenerated stub
    }
}